apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-vol-pod
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: data
    gitRepo:                                                           
      repository: https://github.com/skhurana333/geocoding.git
      revision: main                                              
      directory: blankdir         
