apiVersion: batch/v1
kind: CronJob
metadata:
  name: geocoder-job # name of thejob, kubectl get jobs
spec:
   # left to right ---> Minute(0-59),Hour(0-23),Day of month(1-31),Month of year(1-31), Day of week(0-7, 0 and 7 both sundays).
  schedule: "*/2,*,*,* * * * *"   # runs every 2 mins of every hour,every day of week,every month
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: geocoder
              image: geocoder
              imagePullPolicy: Never
              command: ["java", "-jar", "target/geocoding-1.0-SNAPSHOT.jar"]
